
[package]
name = "smart-contract-tester"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"

[dev-dependencies]
proptest = "1.0"
